[general]
start_dir = "/home/rafal/test/DOWNLOADED/py_files/" # Dir with files to use to test - this dir will not be touched
test_dir = "/home/rafal/test/DOWNLOADED/test_dir/" # Dir to save test results
test_dir2 = "/home/rafal/test/DOWNLOADED/test_dir2/" # Dir to save test results 2
broken_files_dir = "/home/rafal/test/DOWNLOADED/broken_files/" # Dir to save broken_files_results
mode = "find_parse_difference"
black_timeout = 1000000 # In seconds, do not allows to run too much app
depth = 1 # How deep to go in dirs - if in start dir folder to check are directly in start dir, then depth = 1, otherwise setup it to other value
ci_run = false # In CI files from start_dir can be removed, because are unused after first use

# modes
# test_ruff_format_stability
# error_in_format_tool
# check_difference
# find_parse_difference