[package]
name = "automated_fuzzer"
authors = ["Rafał Mikrut <mikrutrafal@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
jwalk = "0.8.1"
rayon = "1.7.0"
rand = "0.8.5"
config = "0.13.3"
zip = "0.6.6"
handsome_logger = "0.7.0"
log = "0.4.20"

strum_macros = "0.25"
strum = { version = "0.25", features = ["derive"] }
