[package]
name = "automated_fuzzer"
authors = ["Rafał Mikrut <mikrutrafal@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
walkdir = "2.3.3"
rayon = "1.7.0"
rand = "0.8.5"
config = "0.13.3"

strum_macros = "0.25"
strum = { version = "0.25", features = ["derive"] }
