[general]
loop_number = 10 # How much creating/removing/checking steps will be executed
broken_files_for_each_file = 1 # Number of broken files that will be created for each 1 valid file
generate_files = true # If true will generate broken files and save them to BROKEN_FILES_DIR(this folder will be removed after each run)
copy_broken_files = true
broken_files_dir = "/home/rafal/Desktop/RunEveryCommand/AA_BROKEN_INPUT_FILES"
minimize_output = true # Tries to remove some lines from output file, remember, that not always minimized file will produce same error - usually minimize output 2-100 times
minimization_attempts = 50 # Attemps to minimize code, if after 25 attempts from 50 minimization completelly

current_mode = "oxc"

[oxc]
app_binary = "/home/rafal/test/oxc/target/release/oxc_cli"
app_config = ""
extensions = "ts,js,mjs,mts"
non_destructive_input_dir = "/home/rafal/Desktop/RunEveryCommand/oxc/Broken"
base_of_valid_files = "/home/rafal/Desktop/RunEveryCommand/AA_JAVASCRIPT_VALID_FILES"
output_dir = "/home/rafal/Desktop/RunEveryCommand/oxc/Broken"

[mypy]
app_binary = "mypy"
app_config = ""
extensions = ""
non_destructive_input_dir = ""
base_of_valid_files = ""
output_dir = ""

[ruff]
app_binary = "ruff"
app_config = "/home/rafal/Desktop/RunEveryCommand/Ruff/ruff.toml"
extensions = ""
non_destructive_input_dir = ""
base_of_valid_files = ""
output_dir = ""

[dlint]
app_binary = "/home/rafal/test/deno_lint/target/release/examples/dlint"
app_config = ""
extensions = ""
non_destructive_input_dir = ""
base_of_valid_files = ""
output_dir = ""

[rome]
app_binary = "rome"
app_config = ""
extensions = ""
non_destructive_input_dir = ""
base_of_valid_files = ""
output_dir = ""