name: 🐧 Ruff ALT No exceptions
on:
  push:
  pull_request:
  schedule:
    - cron: '0 22 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  ruff-alt-no-exceptions-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget

      - name: Install sd
        run: cargo install sd

      - name: Remove exceptions
        run: |
          cat src/apps/ruff.rs
          sd 'const BROKEN_ITEMS: &\[&str\] = &\[[^]]+];' 'const BROKEN_ITEMS: &[&str] = &[];' src/apps/ruff.rs
          sd 'const BROKEN_ITEMS: &\[&str\] = &\[[^]]+];' 'const BROKEN_ITEMS: &[&str] = &[];' src/apps/dlint.rs
          sd 'const BROKEN_ITEMS: &\[&str\] = &\[[^]]+];' 'const BROKEN_ITEMS: &[&str] = &[];' src/apps/rome.rs
          cat src/apps/ruff.rs

      - name: Build
        run: cargo build --release

      - name: Install create_broken_files
        run: cargo install create_broken_files

      - name: Install ruff
        run: cargo install --git https://github.com/astral-sh/ruff.git ruff_cli

      - name: Download and prepare python data files
        run: |
          CURR_DIR=$(pwd)
          mkdir /opt/PYTHON_DATA
          mkdir /opt/TEST_DIR
          mkdir /opt/RESULTS
          
          cd /opt/TEST_DIR
          
          wget https://github.com/qarmin/Automated-Fuzzer/releases/download/test/FILES_1.zip
          unzip FILES_1.zip
          rm FILES_1.zip
          
          cd $CURR_DIR

      - name: Run app
        run: |
          mv fuzz_settings_ci_alt.toml fuzz_settings.toml
          timeout 18000 target/release/automated_fuzzer || true

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: ignore
          name: results
          path: /opt/RESULTS