name: 🐧 Ruff All
on:
  push:
  pull_request:
  schedule:
    - cron: '0 22 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  ruff-normal-ci:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: FINDING_NON_FULLY_CONVERTED_ITEMS
            config-file: settings_ci.toml

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget pipx
      - name: Install ruff
        run: cargo install --git https://github.com/astral-sh/ruff.git ruff_cli
      - name: Install black and check version
        run: |
          pipx install black
          black --version

      - name: Build
        run: |
          cd format
          cargo build --release

      - name: Create folders
        run: |
          mkdir /opt/START_DIR/
          mkdir /opt/TEST_DIR/
          mkdir /opt/TEST_DIR2/
          mkdir /opt/BROKEN_FILES/

      - name: Download and prepare python data files
        run: |
          pwd
          CURR_DIR=$(pwd)
          
          cd /opt/START_DIR
               

          #          mkdir 999
          #          cd 999
          #          wget https://github.com/qarmin/Automated-Fuzzer/releases/download/test/FILES_999.zip
          #          unzip FILES_999.zip
          #          rm FILES_999.zip
          #          cd ..
          
          mkdir 11
          cd 11
          wget https://github.com/qarmin/Automated-Fuzzer/releases/download/test/FILES_11.zip
          unzip FILES_11.zip
          rm FILES_11.zip
          cd ..
          
          mkdir 12
          cd 12
          wget https://github.com/qarmin/Automated-Fuzzer/releases/download/test/FILES_12.zip
          unzip FILES_12.zip
          rm FILES_12.zip
          cd ..

          mkdir 13
          cd 13
          wget https://github.com/qarmin/Automated-Fuzzer/releases/download/test/FILES_13.zip
          unzip FILES_13.zip
          rm FILES_13.zip
          cd ..
          
          cd $CURR_DIR

      - name: Run app
        run: |
          pwd
          cd format
          mv ${{ matrix.config-file }} settings.toml
          target/release/formatter

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: ignore
          name: ${{ matrix.name }}
          path: /opt/BROKEN_FILES

      - name: Exit when found broken files
        run: |
          [ "$(ls -A /opt/BROKEN_FILES)" ] && exit 1 || exit 0

